#合并下载的json文件 用于chat-analytics进行分析
import os
import json
import glob
import re
import csv
import time

# ================= 配置区域 =================
CSV_FILE_PATH = "all_threads.csv"
JSON_FILES_PATTERN = r"E:\discord-backups1.5\discord-backups\backup\**\*.json"
OUTPUT_FILENAME = "merged_final_clean.json"
TARGET_CATEGORY_ID = "1019924310665728022"


# ===========================================

def get_id_from_filename(filename):
    match = re.search(r'\[(\d+)\]\.json$', filename)
    if match:
        return match.group(1)
    return None


def merge_fix_header():
    # --- 1. 读取 CSV ---
    print(f"🚀 [第一步] 读取 CSV 索引...")
    valid_ids = set()
    try:
        with open(CSV_FILE_PATH, 'r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            # 自动找 ID 列
            headers = reader.fieldnames
            if not headers: return
            id_col = next((col for col in headers if col.strip().lower() == 'id'), None)
            if id_col:
                for row in reader:
                    if row.get(id_col):
                        valid_ids.add(str(row[id_col]).strip())
    except Exception as e:
        print(f"❌ CSV 读取错误: {e}")
        return
    print(f"📋 CSV 有效 ID 数: {len(valid_ids)}")

    # --- 2. 扫描文件 ---
    print(f"\n🚀 [第二步] 扫描文件...")
    all_files = glob.glob(JSON_FILES_PATTERN, recursive=True)
    print(f"📊 找到 {len(all_files)} 个文件。")

    # --- 3. 读取并去重 ---
    print(f"\n🚀 [第三步] 读取并清洗...")
    unique_messages = {}

    # 临时存储一个真实的 Guild 信息用于伪造，如果没找到就用默认的
    real_guild_info = {
        "id": "000000000000000000",
        "name": "Merged Server Backup",
        "iconUrl": None
    }

    processed_files = 0

    for index, filepath in enumerate(all_files):
        if filepath.endswith(OUTPUT_FILENAME): continue

        fname = os.path.basename(filepath)
        fid = get_id_from_filename(fname)
        if fid and fid not in valid_ids: continue

        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)

                # 尝试抓取一次真实的公会信息
                if processed_files == 0 and 'guild' in data:
                    real_guild_info = data['guild']

                msgs = data.get('messages', [])
                if msgs:
                    for msg in msgs:
                        if msg.get('id') and msg.get('timestamp'):
                            unique_messages[msg['id']] = msg

                processed_files += 1

        except:
            pass

        if (index + 1) % 5000 == 0:
            print(f"⏳ 进度: {index + 1}/{len(all_files)} | 消息池: {len(unique_messages)}")

    if not unique_messages:
        print("❌ 错误：没有提取到任何消息！")
        return

    # --- 4. 排序 ---
    print(f"\n🚀 [第四步] 正在排序 {len(unique_messages)} 条消息...")
    final_messages_list = list(unique_messages.values())
    final_messages_list.sort(key=lambda x: int(x['id']))

    # --- 5. 构造“完美头部”并写入 (核心修改) ---
    print(f"\n🚀 [第五步] 构造完美头部并写入...")

    # 手动构造一个 chat-analytics 绝对喜欢的标准头部
    # 强制将 type 设为 GuildText (0)，伪装成普通频道
    final_output = {
        "guild": real_guild_info,
        "channel": {
            "id": TARGET_CATEGORY_ID,
            "type": "GuildText",
            "categoryId": TARGET_CATEGORY_ID,
            "category": "日常冲浪区",
            "name": "2025-All-Threads-Merged",
            "topic": "Generated by Merge Script"
        },
        "dateRange": {
            "after": None,
            "before": None
        },
        "exportedAt": "2026-01-16T00:00:00.0000000+00:00",
        "messages": final_messages_list,
        "messageCount": len(final_messages_list)
    }

    with open(OUTPUT_FILENAME, 'w', encoding='utf-8') as f:
        json.dump(final_output, f, ensure_ascii=False, indent=2)

    print("=" * 40)
    print(f"🎉 修复完成！")
    print(f"📂 生成文件: {os.path.abspath(OUTPUT_FILENAME)}")
    print(f"💬 包含消息: {len(final_messages_list)}")
    print(f"ℹ️ 已强制将频道类型伪装为 'GuildText'")
    print("=" * 40)


if __name__ == "__main__":
    merge_fix_header()